# Generated by Django 5.1.7 on 2025-05-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_app", "0002_task_subtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="bgcolor",
            field=models.CharField(default="#1dd38f", max_length=10),
            preserve_default=False,
        ),
    ]
