# Generated by Django 5.1.7 on 2025-05-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_app", "0005_rename_color_hex_profile_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=10),
        ),
    ]
