# Generated by Django 5.1.7 on 2025-05-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_app", "0006_alter_profile_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(default="#9b42d5", max_length=10),
        ),
    ]
