# Generated by Django 5.1.7 on 2025-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_app", "0008_alter_contact_bgcolor_alter_profile_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="bgcolor",
            field=models.CharField(default="#9b2dc6", max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(default="#63be65", max_length=10),
        ),
    ]
