# Generated by Django 5.1.7 on 2025-05-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_app", "0014_alter_contact_bgcolor_alter_profile_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="bgcolor",
            field=models.CharField(default="#bfacdd", max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(default="#a6d5a0", max_length=10),
        ),
    ]
