# Generated by Django 5.1.7 on 2025-05-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_app", "0015_alter_contact_bgcolor_alter_profile_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="bgcolor",
            field=models.CharField(default="#8196bf", max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(default="#34c079", max_length=10),
        ),
    ]
