# Generated by Django 5.1.7 on 2025-05-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_app", "0016_alter_contact_bgcolor_alter_profile_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="bgcolor",
            field=models.CharField(default="#96b46d", max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(default="#0c4ee1", max_length=10),
        ),
    ]
