# Generated by Django 5.1.7 on 2025-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join_app", "0019_alter_contact_bgcolor_alter_profile_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="bgcolor",
            field=models.CharField(default="#6f0b74", max_length=10),
        ),
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(default="#c6b52b", max_length=10),
        ),
    ]
